import "./globals.css";
import Navbar from "./components/navbar";
import AuthProvider from "@/context/AuthProvider";
// import AuthProvider from "./context/AuthProvider";

export const metadata = {
  title: "Chatter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased layt overflow-x-hidden `}>
        <AuthProvider>
          <Navbar />
          <div className="lg:mt-[70px] mt-16">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
