import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased layt overflow-x-hidden `}
      >
        <Navbar />
        <div className="lg:mt-[70px] mt-16">{children}</div>
      </body>
    </html>
  );
}
